FROM golang:1.25-alpine3.23 AS build

ARG GITLEAKS_VERSION=v8.30.1
ARG GO_CRYPTO_VERSION=v0.52.0

RUN apk add --no-cache ca-certificates git
WORKDIR /src
RUN git clone --depth 1 --branch ${GITLEAKS_VERSION} https://github.com/gitleaks/gitleaks.git .
RUN go mod edit -require=golang.org/x/crypto@${GO_CRYPTO_VERSION} \
  && go mod tidy \
  && CGO_ENABLED=0 go build -trimpath -ldflags="-s -w" -o /usr/local/bin/gitleaks .

FROM alpine:3.24

RUN apk add --no-cache ca-certificates

COPY --from=build /usr/local/bin/gitleaks /usr/local/bin/gitleaks

ENTRYPOINT ["gitleaks"]
