allowBuilds:
  '@prisma/engines': true
  prisma: true
  sharp: true
  unrs-resolver: true
overrides:
  '@hono/node-server': 1.19.13
  postcss: 8.5.15
onlyBuiltDependencies:
  - '@prisma/engines'
  - prisma
  - sharp
  - unrs-resolver
